version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "todo-go-database"
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    container_name: "todo-go-app"
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
